# Generated by Django 4.0.3 on 2022-04-11 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='to_do',
            options={'ordering': ['deadline']},
        ),
        migrations.AddField(
            model_name='to_do',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
